// Generated by Wrangler by running `wrangler types`

interface Env {
	OPENAI_API_KEY: string;
	AUTH_OPENAI_POP_CHOICE_WORKER: string;
	SUPABASE_URL: string;
	SUPABASE_API_KEY: string;
	INGESTION_BUCKET: R2Bucket;
}
