name = "openai-pop-choice-embedding-worker"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[r2_buckets]]
binding = "INGESTION_BUCKET"
bucket_name = "pop-choice-ingestion-bucket"
preview_bucket_name = "pop-choice-ingestion-bucket-preview"

[triggers]
crons = ["10 7 * * 2-6"]

[[kv_namespaces]]
binding = "KV_STORE"
id = "1b43874efe6449f9b2aa04f401ea9499"
